CREATE TABLE IF NOT EXISTS callvote (
id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
client_id INT(10) UNSIGNED NOT NULL,
type VARCHAR(20) NOT NULL,
data VARCHAR(40) DEFAULT NULL,
max_num SMALLINT(2) UNSIGNED NOT NULL,
num_yes SMALLINT(2) UNSIGNED NOT NULL,
num_no SMALLINT(2) UNSIGNED NOT NULL,
time_add INT(10) UNSIGNED NOT NULL,
PRIMARY KEY (id),
KEY client_id (client_id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;