CREATE TABLE IF NOT EXISTS jumpruns (
id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
client_id INT(10) UNSIGNED NOT NULL,
mapname VARCHAR(64) NOT NULL,
way_id INT(3) NOT NULL,
way_time INT(10) UNSIGNED NOT NULL,
time_add INT(10) UNSIGNED NOT NULL,
time_edit INT(10) UNSIGNED NOT NULL,
demo VARCHAR(128) DEFAULT NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS jumpways (
id INT(10) NOT NULL AUTO_INCREMENT,
mapname VARCHAR(64) NOT NULL,
way_id INT(3) NOT NULL,
way_name VARCHAR(64) NOT NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;