DROP TABLE IF EXISTS `xlr_bodyparts`;
CREATE TABLE IF NOT EXISTS `xlr_bodyparts` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  CONSTRAINT name UNIQUE (`name`)
);

DROP TABLE IF EXISTS `xlr_mapstats`;
CREATE TABLE IF NOT EXISTS `xlr_mapstats` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) NOT NULL DEFAULT '0',
  CONSTRAINT name UNIQUE (`name`)
);

DROP TABLE IF EXISTS `xlr_opponents`;
CREATE TABLE IF NOT EXISTS `xlr_opponents` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `target_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `killer_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `kills` SMALLINT(5) NOT NULL DEFAULT '0',
  `retals` SMALLINT(5) NOT NULL DEFAULT '0',
  FOREIGN KEY(`target_id`) REFERENCES clients(`id`),
  FOREIGN KEY(`killer_id`) REFERENCES clients(`id`)
);

DROP TABLE IF EXISTS `xlr_playerbody`;
CREATE TABLE IF NOT EXISTS `xlr_playerbody` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `bodypart_id` TINYINT(3) NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  FOREIGN KEY(`bodypart_id`) REFERENCES xlr_bodyparts(`id`),
  FOREIGN KEY(`player_id`) REFERENCES clients(`id`)
);

DROP TABLE IF EXISTS `xlr_playermaps`;
CREATE TABLE IF NOT EXISTS `xlr_playermaps` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `map_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) NOT NULL DEFAULT '0',
  FOREIGN KEY(`map_id`) REFERENCES xlr_mapstats(`id`),
  FOREIGN KEY(`player_id`) REFERENCES clients(`id`)
);

DROP TABLE IF EXISTS `xlr_playerstats`;
CREATE TABLE IF NOT EXISTS `xlr_playerstats` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `client_id` INTEGER(11) NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  `ratio` FLOAT NOT NULL DEFAULT '0',
  `skill` FLOAT NOT NULL DEFAULT '0',
  `assists` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `assistskill` FLOAT NOT NULL DEFAULT '0',
  `curstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `winstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `losestreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) NOT NULL DEFAULT '0',
  `hide` TINYINT(4) NOT NULL DEFAULT '0',
  `fixed_name` VARCHAR(32) NOT NULL DEFAULT '',
  `id_token` VARCHAR(10) NOT NULL DEFAULT '',
  FOREIGN KEY(`client_id`) REFERENCES clients(`id`)
);

DROP TABLE IF EXISTS `xlr_weaponstats`;
CREATE TABLE IF NOT EXISTS `xlr_weaponstats` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(64) NOT NULL DEFAULT '',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  CONSTRAINT name UNIQUE (`name`)
);

DROP TABLE IF EXISTS `xlr_weaponusage`;
CREATE TABLE IF NOT EXISTS `xlr_weaponusage` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `weapon_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  FOREIGN KEY(`weapon_id`) REFERENCES xlr_weaponstats(`id`),
  FOREIGN KEY(`player_id`) REFERENCES clients(`id`)
);

DROP TABLE IF EXISTS `xlr_actionstats`;
CREATE TABLE IF NOT EXISTS `xlr_actionstats` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `count` MEDIUMINT(8) NOT NULL DEFAULT '0',
  CONSTRAINT name UNIQUE (`name`)
);

DROP TABLE IF EXISTS `xlr_playeractions`;
CREATE TABLE IF NOT EXISTS `xlr_playeractions` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `action_id` TINYINT(3) NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) NOT NULL DEFAULT '0',
  `count` MEDIUMINT(8) NOT NULL DEFAULT '0',
  FOREIGN KEY(`action_id`) REFERENCES xlr_actionstats(`id`),
  FOREIGN KEY(`player_id`) REFERENCES clients(`id`)
);

DROP TABLE IF EXISTS `xlr_history_monthly`;
CREATE TABLE IF NOT EXISTS `xlr_history_monthly` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `client_id` INTEGER(11) NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  `ratio` FLOAT NOT NULL DEFAULT '0',
  `skill` FLOAT NOT NULL DEFAULT '0',
  `assists` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `assistskill` FLOAT NOT NULL DEFAULT '0',
  `winstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `losestreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) NOT NULL DEFAULT '0',
  `year` INTEGER(4) NOT NULL,
  `month` INTEGER(2) NOT NULL,
  `week` INTEGER(2) NOT NULL,
  `day` INTEGER(2) NOT NULL
);

DROP TABLE IF EXISTS `xlr_history_weekly`;
CREATE TABLE IF NOT EXISTS `xlr_history_weekly` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `client_id` INTEGER(11) NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) NOT NULL DEFAULT '0',
  `ratio` FLOAT NOT NULL DEFAULT '0',
  `skill` FLOAT NOT NULL DEFAULT '0',
  `assists` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `assistskill` FLOAT NOT NULL DEFAULT '0',
  `winstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `losestreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) NOT NULL DEFAULT '0',
  `year` INTEGER(4) NOT NULL,
  `month` INTEGER(2) NOT NULL,
  `week` INTEGER(2) NOT NULL,
  `day` INTEGER(2) NOT NULL
);

DROP TABLE IF EXISTS `ctime`;
CREATE TABLE IF NOT EXISTS `ctime` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `guid` VARCHAR(36) NOT NULL,
  `came` VARCHAR(11) DEFAULT NULL,
  `gone` VARCHAR(11) DEFAULT NULL,
  `nick` VARCHAR(32) NOT NULL
);