CREATE TABLE IF NOT EXISTS jumpruns (
id SERIAL PRIMARY KEY,
client_id INTEGER NOT NULL,
mapname VARCHAR NOT NULL,
way_id INTEGER NOT NULL,
way_time INTEGER NOT NULL,
time_add INTEGER NOT NULL,
time_edit INTEGER NOT NULL,
demo VARCHAR(128) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS jumpways (
id SERIAL PRIMARY KEY,
mapname VARCHAR NOT NULL,
way_id INTEGER NOT NULL,
way_name VARCHAR NOT NULL);