CREATE TABLE IF NOT EXISTS `%s` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `guid` VARCHAR(36) NOT NULL,
  `came` VARCHAR(11) DEFAULT NULL,
  `gone` VARCHAR(11) DEFAULT NULL,
  `nick` VARCHAR(32) NOT NULL
);