CREATE TABLE IF NOT EXISTS `%s` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(36) NOT NULL,
  `came` VARCHAR(11) DEFAULT NULL,
  `gone` VARCHAR(11) DEFAULT NULL,
  `nick` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;