CREATE TABLE IF NOT EXISTS `xlr_bodyparts` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_mapstats` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_opponents` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `target_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `killer_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `kills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `retals` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `target_id` (`target_id`),
  KEY `killer_id` (`killer_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_playerbody` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bodypart_id` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `bodypart_id` (`bodypart_id`),
  KEY `player_id` (`player_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_playermaps` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `map_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `map_id` (`map_id`),
  KEY `player_id` (`player_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_playerstats` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ratio` FLOAT NOT NULL DEFAULT '0',
  `skill` FLOAT NOT NULL DEFAULT '0',
  `assists` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `assistskill` FLOAT NOT NULL DEFAULT '0',
  `curstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `winstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `losestreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `hide` TINYINT(4) NOT NULL DEFAULT '0',
  `fixed_name` VARCHAR(32) NOT NULL DEFAULT '',  PRIMARY KEY (`id`),
  `id_token` VARCHAR(10) NOT NULL DEFAULT '',
  UNIQUE KEY `client_id` (`client_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_weaponstats` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL DEFAULT '',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_weaponusage` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `weapon_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `weapon_id` (`weapon_id`),
  KEY `player_id` (`player_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_actionstats` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(26) NOT NULL DEFAULT '',
  `count` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_playeractions` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `action_id` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `player_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `count` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `action_id` (`action_id`),
  KEY `player_id` (`player_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_history_monthly` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ratio` FLOAT NOT NULL DEFAULT '0',
  `skill` FLOAT NOT NULL DEFAULT '0',
  `assists` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `assistskill` FLOAT NOT NULL DEFAULT '0',
  `winstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `losestreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `year` INT(4) NOT NULL,
  `month` INT(2) NOT NULL,
  `week` INT(2) NOT NULL,
  `day` INT(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `xlr_history_weekly` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `kills` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `deaths` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `teamkills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `teamdeaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `suicides` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ratio` FLOAT NOT NULL DEFAULT '0',
  `skill` FLOAT NOT NULL DEFAULT '0',
  `assists` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `assistskill` FLOAT NOT NULL DEFAULT '0',
  `winstreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `losestreak` SMALLINT(6) NOT NULL DEFAULT '0',
  `rounds` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `year` INT(4) NOT NULL,
  `month` INT(2) NOT NULL,
  `week` INT(2) NOT NULL,
  `day` INT(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ctime` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(36) NOT NULL,
  `came` VARCHAR(11) DEFAULT NULL,
  `gone` VARCHAR(11) DEFAULT NULL,
  `nick` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;