CREATE TABLE IF NOT EXISTS chatlog (
id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
msg_time INT(10) UNSIGNED NOT NULL,
msg_type ENUM('ALL','TEAM','PM','SQUAD') NOT NULL,
client_id INT(11) UNSIGNED NOT NULL,
client_name VARCHAR(32) NOT NULL,
client_team TINYINT(1) NOT NULL,
msg VARCHAR(528) NOT NULL,
target_id INT(11) UNSIGNED DEFAULT NULL,
target_name VARCHAR(32) DEFAULT NULL,
target_team TINYINT(1) DEFAULT NULL,
PRIMARY KEY (id),
KEY client (client_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS cmdlog (
id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
cmd_time INT(10) UNSIGNED NOT NULL,
admin_id INT(11) UNSIGNED NOT NULL,
admin_name VARCHAR(32) NOT NULL,
command VARCHAR(100) NULL,
data VARCHAR(528) DEFAULT NULL,
result VARCHAR(528) DEFAULT NULL,
PRIMARY KEY (id),
KEY client (admin_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

