CREATE TABLE IF NOT EXISTS jumpruns (
id INTEGER PRIMARY KEY AUTOINCREMENT,
client_id INTEGER(10) NOT NULL,
mapname VARCHAR(64) NOT NULL,
way_id INTEGER(3) NOT NULL,
way_time INTEGER(10) NOT NULL,
time_add INTEGER(10) NOT NULL,
time_edit INTEGER(10) NOT NULL,
demo VARCHAR(128) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS jumpways (
id INTEGER PRIMARY KEY AUTOINCREMENT,
mapname VARCHAR(64) NOT NULL,
way_id INTEGER(3) NOT NULL,
way_name VARCHAR(64) NOT NULL);